// JDK + OpenSSL test; dependencies are supplied in BC_TEST_DEPS (downloaded, never vendored).
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync, mkdirSync, statSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import assert from 'node:assert/strict';
const deps = process.env.BC_TEST_DEPS;
if (!deps) throw new Error('BC_TEST_DEPS directory required');
const work = mkdtempSync(join(tmpdir(), 'azsign-device-identity-'));
const classes = join(work, 'classes'); mkdirSync(classes);
const classpath = `${resolve(deps)}/*`;
execFileSync('javac', ['-cp', classpath, '-d', classes, join(import.meta.dirname, 'AzsignAccessIdentity.java'), join(import.meta.dirname, 'IdentityTest.java')]);
// Also typecheck the Android provider, without running Android stub methods on JVM.
if (process.env.ANDROID_TEST_JAR) execFileSync('javac', ['-cp', `${process.env.ANDROID_TEST_JAR}:${classpath}:${classes}`, '-d', classes,
  ...['AzsignRenewalScheduler.java', 'AzsignRenewalHttp.java', 'AzsignRenewalRuntime.java', 'AzsignAccessPocProvider.java'].map(file => join(import.meta.dirname, file))]);
const id = 'baf3c149-b169-40bf-ac25-47d269930a41';
const dir = join(work, 'device');
const java = (...args) => execFileSync('java', ['-cp', `${classpath}:${classes}`, 'IdentityTest', ...args], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
const openssl = (...args) => execFileSync('openssl', args, { cwd: work, stdio: ['ignore', 'pipe', 'pipe'] });
const csr = java('prepare', dir, id);
assert.equal(csr, java('prepare', dir, id), 're-enrollment must retain key and CSR');
assert.equal(csr, java('prepare-noncrt', dir, id), 'Android non-CRT private key must retain the same valid CSR');
assert.equal(statSync(join(dir, 'identity/key.der')).mode & 0o777, 0o600);
assert.throws(() => java('prepare', dir, 'baf3c149-b169-40bf-ac25-47d269930a42'), 'another identity must not reuse key');
assert.throws(() => java('prepare', dir, '../invalid'), 'reject path traversal');
writeFileSync(join(work, 'request.der'), Buffer.from(csr, 'base64'));
openssl('req', '-inform', 'DER', '-in', 'request.der', '-verify', '-noout');
openssl('req', '-inform', 'DER', '-in', 'request.der', '-out', 'request.pem');
openssl('req', '-x509', '-newkey', 'rsa:2048', '-nodes', '-keyout', 'ca.key', '-out', 'ca.pem', '-days', '2', '-subj', '/CN=Disposable test CA', '-addext', 'basicConstraints=critical,CA:TRUE');
writeFileSync(join(work, 'client.ext'), 'basicConstraints=critical,CA:FALSE\nkeyUsage=critical,digitalSignature\nextendedKeyUsage=clientAuth\n');
openssl('x509', '-req', '-in', 'request.pem', '-CA', 'ca.pem', '-CAkey', 'ca.key', '-set_serial', '1', '-days', '1', '-extfile', 'client.ext', '-out', 'client.pem');
assert.equal(java('verify', dir, id, join(work, 'client.pem'), join(work, 'ca.pem')).trim(), 'verified');
assert.throws(() => java('verify', dir, id, join(work, 'ca.pem'), join(work, 'ca.pem')));
const other = join(work, 'other'); java('prepare', other, id);
assert.throws(() => java('verify', other, id, join(work, 'client.pem'), join(work, 'ca.pem')), 'wrong key rejected');
writeFileSync(join(work, 'server.ext'), 'basicConstraints=critical,CA:FALSE\nkeyUsage=critical,digitalSignature\nextendedKeyUsage=serverAuth\n');
openssl('x509', '-req', '-in', 'request.pem', '-CA', 'ca.pem', '-CAkey', 'ca.key', '-set_serial', '2', '-days', '1', '-extfile', 'server.ext', '-out', 'server.pem');
assert.throws(() => java('verify', dir, id, join(work, 'server.pem'), join(work, 'ca.pem')), 'server-only certificate rejected');
const provider = readFileSync(join(import.meta.dirname, 'AzsignAccessPocProvider.java'), 'utf8');
assert.match(provider, /uid != 2000 && uid != 0/);
assert.match(provider, /File import\/export disabled/);
assert.doesNotMatch(provider, /getPrivate|key\.der/);
console.log('Enrollment crypto passed (CSR proof, stable key, identity/key/EKU rejection, private permissions). Provider compilation: ' + (process.env.ANDROID_TEST_JAR ? 'passed' : 'not run (ANDROID_TEST_JAR missing)'));
